ci(dev-cli): add additional check to ensure binaries are uploaded before continuing CI #14

diff --git a/.github/workflows/dev-cli.yml b/.github/workflows/dev-cli.yml
--- a/.github/workflows/dev-cli.yml
+++ b/.github/workflows/dev-cli.yml
@@ -105,21 +105,34 @@ jobs:
 
       - name: 💾 Publish Binaries to Arweave
         id: publish_binaries
-        # arkb outputs text to the console, the final line being
+        # ArkB may fail to deploy the binaries to Arweave for a number of reasons
+        # 
+        # So before attempting to extract the transaction id from the output
+        # We first check to make sure the success message is output
+        # 
+        # If the deploy was successful, arkb outputs text to the console, the final line being
         # the url of the transaction. We only need the transaction id
         # 
         # So we tail the output and strip the last part of the printed url
         # which should be the transaction id
         run: |
           BINARIES_OUTPUT_DIR=${{ steps.build_binaries.outputs.binaries_output_dir }}
-          ARKB_TRANSACTION_ID=$(\
+          ARKB_RESULT=$(\
             arkb deploy ${BINARIES_OUTPUT_DIR} \
               --no-colors \
               --auto-confirm \
               --wallet ${{ steps.wallet_json.outputs.filePath }} \
-              --use-bundler https://node2.bundlr.network \
-              | tail -1 \
-              | awk -F/ '{print $NF}'
+              --use-bundler https://node2.bundlr.network
+          )
+          echo "${ARKB_RESULT}"
+          if [[ -z $(echo "${ARKB_RESULT}" | awk '/^Data items deployed/') ]]; then
+            echo "Binaries were not successfully deployed to Bundlr! See above logs."
+            exit 1
+          fi
+          ARKB_TRANSACTION_ID=$(\
+            echo "${ARKB_RESULT}" \
+            | tail -1 \
+            | awk -F/ '{print $NF}'
           )
           echo "tx_id=${ARKB_TRANSACTION_ID}" >> $GITHUB_OUTPUT
 
